opam-version: "2.0"
name: "rocq-iris-tutorial"
synopsis: "A tutorial for the Iris framework"
maintainer: "The Iris Tutorial Team"
authors: "The Iris Tutorial Team"
license: "MIT"
homepage: "https://github.com/logsem/iris-tutorial"
dev-repo: "git+https://github.com:logsem/iris-tutorial.git"
bug-reports: "https://github.com/logsem/iris-tutorial/issues"
build: [make "-j%{jobs}%"]
install: []
depends: [
  "rocq-core" { (>= "9.1.0") }
  "rocq-iris" { (>= "4.5.0") }
  "rocq-iris-heap-lang" { (>= "4.5.0") }
]
