ROCQDOCJS_DIR ?= rocqdocjs
EXTRA_DIR = $(ROCQDOCJS_DIR)/extra
ROCQDOCFLAGS ?= \
  --toc --toc-depth 2 --html --interpolate \
  --index indexpage --no-lib-name --parse-comments \
  --with-header $(EXTRA_DIR)/header.html --with-footer $(EXTRA_DIR)/footer.html
export ROCQDOCFLAGS
ROCQMAKEFILE ?= Makefile.rocq
ROCQDOCJS_LN ?= false

rocqdoc: $(ROCQMAKEFILE)
	$(MAKE) -f $^ html
ifeq ($(ROCQDOCJS_LN),true)
	ln -sf ../$(EXTRA_DIR)/resources html
else
	cp -R $(EXTRA_DIR)/resources html
endif

.PHONY: rocqdoc
