name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rocq-prover/docker-opam-action@v1
        with:
          rocq_version: '9.1'
          ocaml_version: '5.5'
          before_install: |
            opam repo add iris-dev https://gitlab.mpi-sws.org/iris/opam.git --all --set-default
          script: |
            git config --global --add safe.directory "*"
            make ci -j$(nproc)
